// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 25 Mar 2023 12:25:31 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package flux provides Go bindings for the Flux Core API.
*/
package flux
